// Generated by scripts/build.mjs; React is supplied by Harness.
window.__ModuleLoader__.load({id:"dsh-file-download",factory:(require)=>{
const module={exports:{}};
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/client.mjs
var client_exports = {};
__export(client_exports, {
  apply: () => apply,
  inject: () => inject,
  install: () => install
});
module.exports = __toCommonJS(client_exports);

// src/download.mjs
var CHUNK_BYTES = 1024 * 1024;
var BUFFER_LIMIT = 32 * 1024 * 1024;
function filenameOf(path) {
  return path.split(/[\\/]/).pop().replace(/[\u0000-\u001f\u007f]/g, "_") || "download";
}
function checkIdentity(info, expected) {
  if (info.version !== expected.version || info.absolutePath !== expected.absolutePath || info.bytes !== expected.bytes) {
    throw new Error("The file changed during the download. Please try again.");
  }
}
function valueOf(result) {
  if (result?.ok === true) return result.value;
  if (result?.ok === false) {
    throw result.error instanceof Error ? result.error : new Error(result.error?.message || "The server refused this file.");
  }
  throw new Error("The server returned an invalid file response.");
}
async function fileInfo(remote, sessionId, path, signal) {
  signal.throwIfAborted();
  const info = valueOf(await remote.stat(sessionId, path, signal));
  signal.throwIfAborted();
  if (!info || !Number.isSafeInteger(info.bytes) || info.bytes < 0 || typeof info.version !== "string" || typeof info.absolutePath !== "string" || !info.absolutePath) {
    throw new Error("The server did not report a valid file size.");
  }
  return info;
}
async function copyFile(remote, sessionId, path, expected, writer, signal, progress) {
  try {
    checkIdentity(await fileInfo(remote, sessionId, path, signal), expected);
    let offset = 0;
    while (offset < expected.bytes) {
      signal.throwIfAborted();
      const page = valueOf(
        await remote.readBytes(
          sessionId,
          path,
          {
            range: { offset, length: Math.min(CHUNK_BYTES, expected.bytes - offset) }
          },
          signal
        )
      );
      signal.throwIfAborted();
      checkIdentity(page, expected);
      if (!(page.data instanceof Uint8Array) || page.offset !== offset || page.data.length === 0 || page.data.length > Math.min(CHUNK_BYTES, expected.bytes - offset) || page.eof !== (offset + page.data.length === expected.bytes)) {
        throw new Error("The server returned an incomplete file. Please try again.");
      }
      await writer.write(page.data);
      offset += page.data.length;
      progress(offset, expected.bytes);
    }
    signal.throwIfAborted();
    checkIdentity(await fileInfo(remote, sessionId, path, signal), expected);
    signal.throwIfAborted();
    await writer.close();
  } catch (error) {
    await writer.abort().catch(() => {
    });
    throw error;
  }
}
function bufferedWriter(limit = BUFFER_LIMIT) {
  const chunks = [];
  let size = 0;
  let complete = false;
  let ended = false;
  return {
    async write(data) {
      if (ended) throw new Error("Download is no longer writable.");
      if (size + data.length > limit)
        throw new Error(
          "This browser needs a save dialog for files larger than 32 MiB. Use Chrome or Edge."
        );
      chunks.push(data.slice());
      size += data.length;
    },
    async close() {
      if (ended) throw new Error("Download is no longer writable.");
      ended = true;
      complete = true;
    },
    async abort() {
      chunks.length = 0;
      size = 0;
      complete = false;
      ended = true;
    },
    blob() {
      if (!complete) throw new Error("Download is incomplete.");
      return new Blob(chunks, { type: "application/octet-stream" });
    }
  };
}

// src/client.mjs
var import_react = __toESM(require("react"), 1);
var ROW = '[data-files-entry="file"][data-files-path]';
var BUTTON = "button[data-dsh-file-download]";
var CSS = `
.dsh-file-download-row{position:relative}
.dsh-file-download-row>button:not([data-dsh-file-download]){padding-inline-end:42px}
button[data-dsh-file-download]{position:absolute;inset-inline-end:6px;top:2px;width:26px;height:26px;display:inline-flex;align-items:center;justify-content:center;padding:4px;border:0;border-radius:4px;background:transparent;color:var(--dsw-alias-label-secondary,currentColor);cursor:pointer;z-index:1}
button[data-dsh-file-download]:hover{background:var(--dsw-alias-interactive-bg-hover,#8882)}
button[data-dsh-file-download]:focus-visible{outline:2px solid var(--dsw-alias-label-primary,currentColor);outline-offset:1px}
button[data-dsh-file-download]:disabled{opacity:.4;cursor:default}
button[data-dsh-file-download] svg{width:16px;height:16px;pointer-events:none}
button[data-dsh-file-download="preview"]{position:static;width:auto;height:28px;gap:5px;padding:4px 7px;font:12px/1.4 system-ui;white-space:nowrap}
[data-dsh-download-status]{position:fixed;bottom:22px;right:22px;max-width:min(420px,90vw);padding:10px 14px;border:1px solid var(--dsw-alias-border-l3,#8886);border-radius:8px;background:var(--dsw-alias-bg-layer-1,#fff);color:var(--dsw-alias-label-primary,#222);font:13px/1.5 system-ui;box-shadow:0 4px 20px #0002;z-index:10000;overflow-wrap:anywhere}
`;
function icon(button, busy = false) {
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("viewBox", "0 0 24 24");
  svg.setAttribute("aria-hidden", "true");
  const path = document.createElementNS(svg.namespaceURI, "path");
  path.setAttribute("d", busy ? "M6 6l12 12M18 6L6 18" : "M12 3v12m-5-5 5 5 5-5M5 16v4h14v-4");
  path.setAttribute("fill", "none");
  path.setAttribute("stroke", "currentColor");
  path.setAttribute("stroke-width", "1.8");
  path.setAttribute("stroke-linecap", "round");
  path.setAttribute("stroke-linejoin", "round");
  svg.append(path);
  button.replaceChildren(svg);
  if (button.dataset.dshFileDownload === "preview") {
    button.append(document.createTextNode(busy ? "Cancel" : "Download"));
  }
}
function install(remote) {
  const style = document.createElement("style");
  style.dataset.dshFileDownloadStyle = "";
  style.textContent = CSS;
  document.head.append(style);
  const status = document.createElement("div");
  status.dataset.dshDownloadStatus = "";
  status.setAttribute("role", "status");
  status.setAttribute("aria-live", "polite");
  status.hidden = true;
  document.body.append(status);
  const active = /* @__PURE__ */ new Map();
  const prepared = /* @__PURE__ */ new WeakMap();
  const urls = /* @__PURE__ */ new Map();
  let disposed = false;
  let statusTimer;
  const notify = (text, error = false) => {
    if (disposed) return;
    clearTimeout(statusTimer);
    status.textContent = text;
    status.hidden = false;
    statusTimer = setTimeout(
      () => {
        status.hidden = true;
      },
      error ? 15e3 : 5e3
    );
  };
  const contextOf = (row) => ({
    path: row.getAttribute("data-files-path"),
    sessionId: row.closest("[data-sidebar-right-session]")?.getAttribute("data-sidebar-right-session")
  });
  async function download(button, getContext) {
    if (active.has(button)) {
      active.get(button).abort();
      return;
    }
    const { path, sessionId } = getContext();
    if (!path || !sessionId) return;
    if (active.size >= 2) {
      notify("Two downloads are running. Wait for one to finish.");
      return;
    }
    const controller = new AbortController();
    const { signal } = controller;
    const name = filenameOf(path);
    active.set(button, controller);
    button.setAttribute("aria-label", `Cancel download of ${name}`);
    button.title = `Cancel download of ${name}`;
    icon(button, true);
    let writer;
    let buffered;
    try {
      const cached = prepared.get(button);
      prepared.delete(button);
      let info;
      if (cached?.path === path && cached.sessionId === sessionId) {
        const handle = await window.showSaveFilePicker({ suggestedName: name });
        info = await fileInfo(remote, sessionId, path, signal);
        writer = await handle.createWritable();
      } else {
        info = await fileInfo(remote, sessionId, path, signal);
        if (info.bytes > BUFFER_LIMIT) {
          if (typeof window.showSaveFilePicker !== "function") {
            throw new Error("Files larger than 32 MiB need Chrome or Edge's save dialog.");
          }
          prepared.set(button, { path, sessionId });
          const handle = await window.showSaveFilePicker({ suggestedName: name });
          prepared.delete(button);
          writer = await handle.createWritable();
        } else {
          buffered = bufferedWriter();
          writer = buffered;
        }
      }
      notify(`Downloading ${name}…`);
      await copyFile(remote, sessionId, path, info, writer, signal, (done, total) => {
        button.title = `Cancel download of ${name} (${Math.floor(done / total * 100)}%)`;
      });
      if (buffered) {
        const url = URL.createObjectURL(buffered.blob());
        const anchor = document.createElement("a");
        anchor.href = url;
        anchor.download = name;
        anchor.hidden = true;
        document.body.append(anchor);
        anchor.click();
        anchor.remove();
        urls.set(
          url,
          setTimeout(() => {
            URL.revokeObjectURL(url);
            urls.delete(url);
          }, 6e4)
        );
      }
      notify(buffered ? `Download started: ${name}` : `Saved ${name}`);
    } catch (error) {
      if (writer) await writer.abort().catch(() => {
      });
      if (signal.aborted || error?.name === "AbortError") {
        prepared.delete(button);
        notify(`Download cancelled: ${name}`);
      } else if (["SecurityError", "NotAllowedError"].includes(error?.name) && prepared.has(button)) {
        notify("Click Download again to choose where to save this large file.", true);
      } else {
        prepared.delete(button);
        notify(`Download failed: ${String(error?.message || error).slice(0, 180)}`, true);
      }
    } finally {
      active.delete(button);
      if (!disposed && button.isConnected) {
        const current = getContext();
        const label = `Download ${filenameOf(current.path || path)}`;
        button.setAttribute("aria-label", label);
        button.title = label;
        button.disabled = !current.sessionId;
        icon(button);
      }
    }
  }
  function attach(row) {
    const { path, sessionId } = contextOf(row);
    let button = [...row.children].find((child) => child.matches(BUTTON));
    if (!button) {
      button = document.createElement("button");
      button.type = "button";
      button.dataset.dshFileDownload = "";
      button.addEventListener("click", (event) => {
        event.preventDefault();
        event.stopPropagation();
        void download(button, () => contextOf(row));
      });
      row.classList.add("dsh-file-download-row");
      row.append(button);
      icon(button);
    }
    if (!active.has(button)) {
      const label = `Download ${filenameOf(path)}`;
      button.setAttribute("aria-label", label);
      button.title = label;
      button.disabled = !sessionId;
    }
  }
  function scan(node) {
    if (!(node instanceof Element)) return;
    if (node.matches(ROW)) attach(node);
    node.querySelectorAll(ROW).forEach(attach);
  }
  const observer = new MutationObserver((records) => {
    for (const record of records) {
      if (record.type === "attributes") scan(record.target);
      else for (const node of record.addedNodes) scan(node);
    }
  });
  scan(document.body);
  observer.observe(document.body, {
    childList: true,
    subtree: true,
    attributes: true,
    attributeFilter: ["data-files-path", "data-sidebar-right-session"]
  });
  function PreviewDownload({ absolutePath, sessionId }) {
    const host = import_react.default.useRef(null);
    import_react.default.useEffect(() => {
      const button = document.createElement("button");
      button.type = "button";
      button.dataset.dshFileDownload = "preview";
      const getContext = () => {
        const address = host.current?.closest("[data-textpreview-url]")?.getAttribute("data-textpreview-url");
        const prefix = "dsh-resource://file/session/";
        let ownerSession = sessionId;
        if (address?.startsWith(prefix)) {
          try {
            ownerSession = decodeURIComponent(address.slice(prefix.length).split("/")[0]);
          } catch {
            return {};
          }
        }
        return { path: absolutePath, sessionId: ownerSession };
      };
      const label = `Download ${filenameOf(absolutePath)}`;
      button.setAttribute("aria-label", label);
      button.title = label;
      button.disabled = !absolutePath || !getContext().sessionId;
      icon(button);
      button.addEventListener("click", (event) => {
        event.preventDefault();
        event.stopPropagation();
        void download(button, getContext);
      });
      host.current.append(button);
      return () => {
        active.get(button)?.abort();
        prepared.delete(button);
        button.remove();
      };
    }, [absolutePath, sessionId]);
    return import_react.default.createElement("span", { ref: host, "data-dsh-preview-download": "" });
  }
  const dispose = () => {
    disposed = true;
    observer.disconnect();
    clearTimeout(statusTimer);
    for (const controller of active.values()) controller.abort();
    for (const [url, timer] of urls) {
      clearTimeout(timer);
      URL.revokeObjectURL(url);
    }
    document.querySelectorAll(BUTTON).forEach((button) => button.remove());
    document.querySelectorAll(".dsh-file-download-row").forEach((row) => row.classList.remove("dsh-file-download-row"));
    style.remove();
    status.remove();
  };
  return { PreviewDownload, dispose };
}
var inject = ["remote", "remote.workspaceFiles", "slots"];
function apply(ctx) {
  ctx.effect(() => {
    const ui = install(ctx.remote.workspaceFiles);
    const unregister = ctx.slots.inject(
      "sidebar.right.tab.document.actions",
      () => ctx.slots.register(
        {
          name: "sidebar.right.tab.document.actions",
          id: "dsh-file-download",
          order: 100
        },
        ui.PreviewDownload
      )
    );
    return () => {
      unregister();
      ui.dispose();
    };
  });
}
return module.exports;
}});
