// Generated by scripts/build.mjs; React is supplied by Harness.
window.__ModuleLoader__.load({id:"dsh-file-download",factory:(require)=>{
const module={exports:{}};
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/client.mjs
var client_exports = {};
__export(client_exports, {
  apply: () => apply,
  inject: () => inject,
  install: () => install
});
module.exports = __toCommonJS(client_exports);

// src/download.mjs
var CHUNK_BYTES = 1024 * 1024;
var BUFFER_LIMIT = 32 * 1024 * 1024;
function filenameOf(path) {
  return path.split(/[\\/]/).pop().replace(/[\u0000-\u001f\u007f]/g, "_") || "download";
}
function checkIdentity(info, expected) {
  if (info.version !== expected.version || info.absolutePath !== expected.absolutePath || info.bytes !== expected.bytes) {
    throw new Error("The file changed during the download. Please try again.");
  }
}
function valueOf(result) {
  if (result?.ok === true) return result.value;
  if (result?.ok === false) {
    throw result.error instanceof Error ? result.error : new Error(result.error?.message || "The server refused this file.");
  }
  throw new Error("The server returned an invalid file response.");
}
async function fileInfo(remote, sessionId, path, signal) {
  signal.throwIfAborted();
  const info = valueOf(await remote.stat(sessionId, path, signal));
  signal.throwIfAborted();
  if (!info || !Number.isSafeInteger(info.bytes) || info.bytes < 0 || typeof info.version !== "string" || typeof info.absolutePath !== "string" || !info.absolutePath) {
    throw new Error("The server did not report a valid file size.");
  }
  return info;
}
async function copyFile(remote, sessionId, path, expected, writer, signal, progress) {
  try {
    checkIdentity(await fileInfo(remote, sessionId, path, signal), expected);
    let offset = 0;
    while (offset < expected.bytes) {
      signal.throwIfAborted();
      const page = valueOf(
        await remote.readBytes(
          sessionId,
          path,
          {
            range: { offset, length: Math.min(CHUNK_BYTES, expected.bytes - offset) }
          },
          signal
        )
      );
      signal.throwIfAborted();
      checkIdentity(page, expected);
      if (!(page.data instanceof Uint8Array) || page.offset !== offset || page.data.length === 0 || page.data.length > Math.min(CHUNK_BYTES, expected.bytes - offset) || page.eof !== (offset + page.data.length === expected.bytes)) {
        throw new Error("The server returned an incomplete file. Please try again.");
      }
      await writer.write(page.data);
      offset += page.data.length;
      progress(offset, expected.bytes);
    }
    signal.throwIfAborted();
    checkIdentity(await fileInfo(remote, sessionId, path, signal), expected);
    signal.throwIfAborted();
    await writer.close();
  } catch (error) {
    await writer.abort().catch(() => {
    });
    throw error;
  }
}
function bufferedWriter(limit = BUFFER_LIMIT) {
  const chunks = [];
  let size = 0;
  let complete = false;
  let ended = false;
  return {
    async write(data) {
      if (ended) throw new Error("Download is no longer writable.");
      if (size + data.length > limit)
        throw new Error(
          "This browser needs a save dialog for files larger than 32 MiB. Use Chrome or Edge."
        );
      chunks.push(data.slice());
      size += data.length;
    },
    async close() {
      if (ended) throw new Error("Download is no longer writable.");
      ended = true;
      complete = true;
    },
    async abort() {
      chunks.length = 0;
      size = 0;
      complete = false;
      ended = true;
    },
    blob() {
      if (!complete) throw new Error("Download is incomplete.");
      return new Blob(chunks, { type: "application/octet-stream" });
    }
  };
}

// src/zip.mjs
var ZIP_LIMIT = 4294967295;
var ENTRY_LIMIT = 1e4;
var METADATA_LIMIT = 8 * 1024 * 1024;
var encoder = new TextEncoder();
var decoder = new TextDecoder();
var crcTable = Uint32Array.from({ length: 256 }, (_, value) => {
  for (let bit = 0; bit < 8; bit++) value = value >>> 1 ^ (value & 1 ? 3988292384 : 0);
  return value >>> 0;
});
function crc32(data, crc = 4294967295) {
  for (const byte of data) crc = crc >>> 8 ^ crcTable[(crc ^ byte) & 255];
  return crc >>> 0;
}
function safeComponent(name) {
  if (typeof name !== "string" || !name || name === "." || name === ".." || /[\\/:\u0000-\u001f\u007f]/.test(name) || decoder.decode(encoder.encode(name)) !== name) {
    throw new Error("A folder contains a name that cannot be safely represented in a ZIP.");
  }
  return name;
}
function zipEntry(name, directory, info, path) {
  const components = name.replace(/\/$/, "").split("/");
  components.forEach(safeComponent);
  const nameBytes = encoder.encode(name);
  if (nameBytes.length > 65535) throw new Error("An archive path is too long for ZIP.");
  return { name, nameBytes, directory, info, path, bytes: directory ? 0 : info.bytes };
}
function zipBudget() {
  let bytes = 22, metadata = 0;
  let count = 0;
  return {
    get bytes() {
      return bytes;
    },
    add(entry) {
      if (++count > ENTRY_LIMIT)
        throw new Error("Folders with more than 10,000 ZIP entries are not supported.");
      const recordBytes = 76 + entry.nameBytes.length * 2 + (entry.directory ? 0 : 16);
      metadata += recordBytes;
      bytes += entry.bytes + recordBytes;
      if (!Number.isSafeInteger(entry.bytes) || entry.bytes < 0 || bytes >= ZIP_LIMIT) {
        throw new Error("This folder exceeds the ZIP32 archive limit (just under 4 GiB).");
      }
      if (metadata > METADATA_LIMIT)
        throw new Error("This folder exceeds the ZIP metadata limit (8 MiB).");
      return bytes;
    }
  };
}
function zipSize(entries) {
  const budget = zipBudget();
  for (const entry of entries) budget.add(entry);
  return budget.bytes;
}
function record(size, signature) {
  const data = new Uint8Array(size);
  const view = new DataView(data.buffer);
  view.setUint32(0, signature, true);
  return { data, view };
}
function localHeader(entry) {
  const { data, view } = record(30 + entry.nameBytes.length, 67324752);
  view.setUint16(4, 20, true);
  view.setUint16(6, entry.directory ? 2048 : 2056, true);
  view.setUint16(12, 33, true);
  view.setUint16(26, entry.nameBytes.length, true);
  data.set(entry.nameBytes, 30);
  return data;
}
function descriptor(crc, bytes) {
  const { data, view } = record(16, 134695760);
  view.setUint32(4, crc, true);
  view.setUint32(8, bytes, true);
  view.setUint32(12, bytes, true);
  return data;
}
function centralHeader(entry, crc, offset) {
  const { data, view } = record(46 + entry.nameBytes.length, 33639248);
  view.setUint16(4, 20, true);
  view.setUint16(6, 20, true);
  view.setUint16(8, entry.directory ? 2048 : 2056, true);
  view.setUint16(14, 33, true);
  view.setUint32(16, crc, true);
  view.setUint32(20, entry.bytes, true);
  view.setUint32(24, entry.bytes, true);
  view.setUint16(28, entry.nameBytes.length, true);
  view.setUint32(38, entry.directory ? 16 : 32, true);
  view.setUint32(42, offset, true);
  data.set(entry.nameBytes, 46);
  return data;
}
function endRecord(count, size, offset) {
  const { data, view } = record(22, 101010256);
  view.setUint16(8, count, true);
  view.setUint16(10, count, true);
  view.setUint32(12, size, true);
  view.setUint32(16, offset, true);
  return data;
}

// src/archive.mjs
function archiveName(path) {
  const basename = filenameOf(path.replace(/[\\/]+$/, ""));
  const root = !path || basename === "." || /^[A-Za-z]:$/.test(basename) || !path.replace(/[\\/]/g, "") ? "workspace" : basename;
  return `${root}.zip`;
}
async function listDirectory(remote, sessionId, path, signal) {
  signal.throwIfAborted();
  const listing = valueOf(await remote.list(sessionId, path || ".", signal));
  signal.throwIfAborted();
  if (!listing || typeof listing.path !== "string" || !Array.isArray(listing.entries) || typeof listing.truncated !== "boolean") {
    throw new Error("The server returned an invalid folder listing.");
  }
  if (listing.truncated)
    throw new Error(
      "Harness truncated a folder listing. Increase its maxEntries setting before downloading this folder."
    );
  if (listing.path) listing.path.split("/").forEach(safeComponent);
  const names = /* @__PURE__ */ new Set();
  const entries = listing.entries.map((entry) => {
    safeComponent(entry?.name);
    if (names.has(entry.name)) throw new Error("The server returned duplicate folder entries.");
    names.add(entry.name);
    if (!["file", "directory"].includes(entry.type))
      throw new Error("This folder contains a symlink or special entry that cannot be archived.");
    return { name: entry.name, type: entry.type };
  }).sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0);
  return { path: listing.path, entries };
}
async function planArchive(remote, sessionId, path, signal) {
  const name = archiveName(path);
  const root = name.slice(0, -4);
  const entries = [zipEntry(`${root}/`, true)];
  const directories = [];
  const budget = zipBudget();
  budget.add(entries[0]);
  async function visit(requestPath, archivePath, depth) {
    if (depth > 64) throw new Error("Folders nested more than 64 levels are not supported.");
    const listing = await listDirectory(remote, sessionId, requestPath, signal);
    directories.push(listing);
    for (const child of listing.entries) {
      signal.throwIfAborted();
      if (entries.length >= ENTRY_LIMIT)
        throw new Error("Folders with more than 10,000 ZIP entries are not supported.");
      const childPath = listing.path ? `${listing.path}/${child.name}` : child.name;
      const directory = child.type === "directory";
      const info = directory ? void 0 : await fileInfo(remote, sessionId, childPath, signal);
      const relative = `${archivePath}/${child.name}`;
      const entry = zipEntry(relative + (directory ? "/" : ""), directory, info, childPath);
      budget.add(entry);
      entries.push(entry);
      if (directory) await visit(childPath, relative, depth + 1);
    }
  }
  await visit(path || ".", root, 0);
  return { name, bytes: budget.bytes, entries, directories };
}
async function copyArchive(remote, sessionId, plan, writer, signal, progress) {
  let written = 0;
  const central = [];
  const write = async (data) => {
    signal.throwIfAborted();
    await writer.write(data);
    signal.throwIfAborted();
    written += data.length;
    progress(written, plan.bytes);
  };
  try {
    assertPlan(plan);
    for (const entry of plan.entries) {
      const offset2 = written;
      await write(localHeader(entry));
      let crc = 4294967295;
      if (!entry.directory) {
        await copyFile(
          remote,
          sessionId,
          entry.path,
          entry.info,
          {
            async write(data) {
              crc = crc32(data, crc);
              await write(data);
            },
            async close() {
            },
            async abort() {
              await writer.abort();
            }
          },
          signal,
          () => {
          }
        );
        crc = (crc ^ 4294967295) >>> 0;
        await write(descriptor(crc, entry.bytes));
      } else crc = 0;
      central.push(centralHeader(entry, crc, offset2));
    }
    for (const expected of plan.directories) {
      const current = await listDirectory(remote, sessionId, expected.path, signal);
      if (JSON.stringify(current) !== JSON.stringify(expected))
        throw new Error("The folder changed during the download. Please try again.");
    }
    for (const entry of plan.entries) {
      if (!entry.directory)
        checkIdentity(await fileInfo(remote, sessionId, entry.path, signal), entry.info);
    }
    const offset = written;
    for (const header of central) await write(header);
    const size = written - offset;
    await write(endRecord(plan.entries.length, size, offset));
    if (written !== plan.bytes) throw new Error("The archive size did not match its plan.");
    signal.throwIfAborted();
    await writer.close();
  } catch (error) {
    await writer.abort().catch(() => {
    });
    throw error;
  }
}
function assertPlan(plan) {
  if (zipSize(plan.entries) !== plan.bytes) throw new Error("The archive plan is invalid.");
}

// src/client.mjs
var import_react = __toESM(require("react"), 1);
var ROW = ':is([data-files-entry="file"],[data-files-entry="directory"])[data-files-path]';
var BUTTON = "button[data-dsh-file-download]";
var CSS = `
.dsh-file-download-row{position:relative}
.dsh-file-download-row>button:not([data-dsh-file-download]){padding-inline-end:42px}
button[data-dsh-file-download]{position:absolute;inset-inline-end:6px;top:2px;width:26px;height:26px;display:inline-flex;align-items:center;justify-content:center;padding:4px;border:0;border-radius:4px;background:transparent;color:var(--dsw-alias-label-secondary,currentColor);cursor:pointer;z-index:1}
button[data-dsh-file-download]:hover{background:var(--dsw-alias-interactive-bg-hover,#8882)}
button[data-dsh-file-download]:focus-visible{outline:2px solid var(--dsw-alias-label-primary,currentColor);outline-offset:1px}
button[data-dsh-file-download]:disabled{opacity:.4;cursor:default}
button[data-dsh-file-download] svg{width:16px;height:16px;pointer-events:none}
button[data-dsh-file-download="preview"]{position:static;width:auto;height:28px;gap:5px;padding:4px 7px;font:12px/1.4 system-ui;white-space:nowrap}
[data-dsh-download-status]{position:fixed;bottom:22px;right:22px;max-width:min(420px,90vw);padding:10px 14px;border:1px solid var(--dsw-alias-border-l3,#8886);border-radius:8px;background:var(--dsw-alias-bg-layer-1,#fff);color:var(--dsw-alias-label-primary,#222);font:13px/1.5 system-ui;box-shadow:0 4px 20px #0002;z-index:10000;overflow-wrap:anywhere}
`;
function icon(button, busy = false) {
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("viewBox", "0 0 24 24");
  svg.setAttribute("aria-hidden", "true");
  const path = document.createElementNS(svg.namespaceURI, "path");
  path.setAttribute("d", busy ? "M6 6l12 12M18 6L6 18" : "M12 3v12m-5-5 5 5 5-5M5 16v4h14v-4");
  path.setAttribute("fill", "none");
  path.setAttribute("stroke", "currentColor");
  path.setAttribute("stroke-width", "1.8");
  path.setAttribute("stroke-linecap", "round");
  path.setAttribute("stroke-linejoin", "round");
  svg.append(path);
  button.replaceChildren(svg);
  if (button.dataset.dshFileDownload === "preview") {
    button.append(
      document.createTextNode(
        busy ? "Cancel" : button.dataset.dshDownloadKind === "directory" ? "Download ZIP" : "Download"
      )
    );
  }
}
function install(remote) {
  const style = document.createElement("style");
  style.dataset.dshFileDownloadStyle = "";
  style.textContent = CSS;
  document.head.append(style);
  const status = document.createElement("div");
  status.dataset.dshDownloadStatus = "";
  status.setAttribute("role", "status");
  status.setAttribute("aria-live", "polite");
  status.hidden = true;
  document.body.append(status);
  const active = /* @__PURE__ */ new Map();
  const prepared = /* @__PURE__ */ new WeakMap();
  const urls = /* @__PURE__ */ new Map();
  let disposed = false;
  let statusTimer;
  const notify = (text, error = false) => {
    if (disposed) return;
    clearTimeout(statusTimer);
    status.textContent = text;
    status.hidden = false;
    statusTimer = setTimeout(
      () => {
        status.hidden = true;
      },
      error ? 15e3 : 5e3
    );
  };
  const contextOf = (row) => ({
    path: row.getAttribute("data-files-path"),
    directory: row.getAttribute("data-files-entry") === "directory",
    sessionId: row.closest("[data-sidebar-right-session]")?.getAttribute("data-sidebar-right-session")
  });
  async function download(button, getContext) {
    if (active.has(button)) {
      active.get(button).abort();
      return;
    }
    const { path, sessionId, directory = false } = getContext();
    if (typeof path !== "string" || !path && !directory || !sessionId) return;
    if (active.size >= 2) {
      notify("Two downloads are running. Wait for one to finish.");
      return;
    }
    const controller = new AbortController();
    const { signal } = controller;
    const name = directory ? archiveName(path) : filenameOf(path);
    active.set(button, controller);
    button.setAttribute("aria-label", `Cancel download of ${name}`);
    button.title = `Cancel download of ${name}`;
    icon(button, true);
    let writer;
    let buffered;
    try {
      if (directory) notify(`Preparing ${name}…`);
      const cached = prepared.get(button);
      prepared.delete(button);
      let info;
      const prepare = () => directory ? planArchive(remote, sessionId, path, signal) : fileInfo(remote, sessionId, path, signal);
      if (directory && typeof window.showSaveFilePicker === "function") {
        const handle = await window.showSaveFilePicker({ suggestedName: name });
        info = await prepare();
        writer = await handle.createWritable();
      } else if (cached?.path === path && cached.sessionId === sessionId && cached.directory === directory) {
        const handle = await window.showSaveFilePicker({ suggestedName: name });
        info = await prepare();
        writer = await handle.createWritable();
      } else {
        info = await prepare();
        if (info.bytes > BUFFER_LIMIT) {
          if (typeof window.showSaveFilePicker !== "function") {
            throw new Error("Downloads larger than 32 MiB need Chrome or Edge's save dialog.");
          }
          prepared.set(button, { path, sessionId, directory });
          const handle = await window.showSaveFilePicker({ suggestedName: name });
          prepared.delete(button);
          writer = await handle.createWritable();
        } else {
          buffered = bufferedWriter();
          writer = buffered;
        }
      }
      notify(`Downloading ${name}…`);
      const progress = (done, total) => {
        button.title = `Cancel download of ${name} (${Math.floor(done / total * 100)}%)`;
      };
      if (directory) await copyArchive(remote, sessionId, info, writer, signal, progress);
      else await copyFile(remote, sessionId, path, info, writer, signal, progress);
      if (buffered) {
        const url = URL.createObjectURL(buffered.blob());
        const anchor = document.createElement("a");
        anchor.href = url;
        anchor.download = name;
        anchor.hidden = true;
        document.body.append(anchor);
        anchor.click();
        anchor.remove();
        urls.set(
          url,
          setTimeout(() => {
            URL.revokeObjectURL(url);
            urls.delete(url);
          }, 6e4)
        );
      }
      notify(buffered ? `Download started: ${name}` : `Saved ${name}`);
    } catch (error) {
      if (writer) await writer.abort().catch(() => {
      });
      if (signal.aborted || error?.name === "AbortError") {
        prepared.delete(button);
        notify(`Download cancelled: ${name}`);
      } else if (["SecurityError", "NotAllowedError"].includes(error?.name) && prepared.has(button)) {
        notify("Click Download again to choose where to save this large file.", true);
      } else {
        prepared.delete(button);
        notify(`Download failed: ${String(error?.message || error).slice(0, 180)}`, true);
      }
    } finally {
      active.delete(button);
      if (!disposed && button.isConnected) {
        const current = getContext();
        const label = current.directory ? `Download ${archiveName(current.path || path).slice(0, -4)} as ZIP` : `Download ${filenameOf(current.path || path)}`;
        button.setAttribute("aria-label", label);
        button.title = label;
        button.disabled = !current.sessionId;
        icon(button);
      }
    }
  }
  function attach(row) {
    const { path, sessionId, directory } = contextOf(row);
    let button = [...row.children].find((child) => child.matches(BUTTON));
    if (!button) {
      button = document.createElement("button");
      button.type = "button";
      button.dataset.dshFileDownload = "";
      button.addEventListener("click", (event) => {
        event.preventDefault();
        event.stopPropagation();
        void download(button, () => contextOf(row));
      });
      row.classList.add("dsh-file-download-row");
      row.append(button);
      icon(button);
    }
    if (!active.has(button)) {
      button.dataset.dshDownloadKind = directory ? "directory" : "file";
      const label = directory ? `Download ${archiveName(path).slice(0, -4)} as ZIP` : `Download ${filenameOf(path)}`;
      button.setAttribute("aria-label", label);
      button.title = label;
      button.disabled = !sessionId;
    }
  }
  function scan(node) {
    if (!(node instanceof Element)) return;
    if (node.matches(ROW)) attach(node);
    node.querySelectorAll(ROW).forEach(attach);
  }
  const observer = new MutationObserver((records) => {
    for (const record2 of records) {
      if (record2.type === "attributes") {
        if (record2.attributeName === "data-files-entry" && !record2.target.matches(ROW)) {
          const button = [...record2.target.children].find((child) => child.matches(BUTTON));
          active.get(button)?.abort();
          button?.remove();
          record2.target.classList.remove("dsh-file-download-row");
        }
        scan(record2.target);
      } else for (const node of record2.addedNodes) scan(node);
    }
  });
  scan(document.body);
  observer.observe(document.body, {
    childList: true,
    subtree: true,
    attributes: true,
    attributeFilter: ["data-files-path", "data-files-entry", "data-sidebar-right-session"]
  });
  function ToolbarDownload({ absolutePath, sessionId, directory = false }) {
    const host = import_react.default.useRef(null);
    import_react.default.useEffect(() => {
      const button = document.createElement("button");
      button.type = "button";
      button.dataset.dshFileDownload = "preview";
      button.dataset.dshDownloadKind = directory ? "directory" : "file";
      const getContext = () => {
        const address = host.current?.closest("[data-textpreview-url]")?.getAttribute("data-textpreview-url");
        const prefix = "dsh-resource://file/session/";
        let ownerSession = sessionId || host.current?.closest("[data-sidebar-right-session]")?.getAttribute("data-sidebar-right-session");
        if (!directory && address?.startsWith(prefix)) {
          try {
            ownerSession = decodeURIComponent(address.slice(prefix.length).split("/")[0]);
          } catch {
            return {};
          }
        }
        return { path: absolutePath, sessionId: ownerSession, directory };
      };
      const label = directory ? `Download ${archiveName(absolutePath || "").slice(0, -4)} as ZIP` : `Download ${filenameOf(absolutePath || "")}`;
      button.setAttribute("aria-label", label);
      button.title = label;
      button.disabled = typeof absolutePath !== "string" || !absolutePath && !directory || !getContext().sessionId;
      icon(button);
      button.addEventListener("click", (event) => {
        event.preventDefault();
        event.stopPropagation();
        void download(button, getContext);
      });
      host.current.append(button);
      return () => {
        active.get(button)?.abort();
        prepared.delete(button);
        button.remove();
      };
    }, [absolutePath, sessionId, directory]);
    return import_react.default.createElement("span", { ref: host, "data-dsh-preview-download": "" });
  }
  const PreviewDownload = (props) => import_react.default.createElement(ToolbarDownload, props);
  const FolderDownload = (props) => import_react.default.createElement(ToolbarDownload, { ...props, directory: true });
  const dispose = () => {
    disposed = true;
    observer.disconnect();
    clearTimeout(statusTimer);
    for (const controller of active.values()) controller.abort();
    for (const [url, timer] of urls) {
      clearTimeout(timer);
      URL.revokeObjectURL(url);
    }
    document.querySelectorAll(BUTTON).forEach((button) => button.remove());
    document.querySelectorAll(".dsh-file-download-row").forEach((row) => row.classList.remove("dsh-file-download-row"));
    style.remove();
    status.remove();
  };
  return { PreviewDownload, FolderDownload, dispose };
}
var inject = ["remote", "remote.workspaceFiles", "slots"];
function apply(ctx) {
  ctx.effect(() => {
    const ui = install(ctx.remote.workspaceFiles);
    const unregister = ctx.slots.inject(
      "sidebar.right.tab.document.actions",
      () => ctx.slots.register(
        {
          name: "sidebar.right.tab.document.actions",
          id: "dsh-file-download",
          order: 100
        },
        ui.PreviewDownload
      )
    );
    const unregisterFolders = ctx.slots.inject(
      "sidebar.right.tab.files.actions",
      () => ctx.slots.register(
        {
          name: "sidebar.right.tab.files.actions",
          id: "dsh-folder-download",
          order: 100
        },
        ui.FolderDownload
      )
    );
    return () => {
      unregister();
      unregisterFolders();
      ui.dispose();
    };
  });
}
return module.exports;
}});
