import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));
const pkg = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));
const check = process.argv.includes("--check");
const shared = {
  absWorkingDir: root,
  bundle: true,
  write: false,
  charset: "utf8",
  legalComments: "none",
  logLevel: "silent",
};
const client = await build({
  ...shared,
  entryPoints: ["src/client.mjs"],
  outfile: "lib/client.js",
  platform: "browser",
  format: "cjs",
  target: "es2022",
  external: ["react"],
  banner: {
    js: `// Generated by scripts/build.mjs; React is supplied by Harness.\nwindow.__ModuleLoader__.load({id:${JSON.stringify(pkg.name)},factory:(require)=>{\nconst module={exports:{}};`,
  },
  footer: { js: "return module.exports;\n}});" },
});
const server = await build({
  ...shared,
  entryPoints: ["src/index.mjs"],
  outfile: "lib/index.js",
  platform: "node",
  format: "esm",
  target: "node22",
});

await mkdir(path.join(root, "lib"), { recursive: true });
for (const output of [...client.outputFiles, ...server.outputFiles]) {
  if (check) {
    const saved = await readFile(output.path);
    if (!saved.equals(Buffer.from(output.contents))) {
      throw new Error(`${path.relative(root, output.path)} is stale. Run npm run build.`);
    }
  } else {
    await writeFile(output.path, output.contents);
  }
}
console.log(check ? "Prebuilt modules are current." : "Built server and browser modules.");
